apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "containerization-assist.fullname" . }}-kaniko
  labels:
    {{- include "containerization-assist.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "credHelpers": {
        "*.azurecr.io": "{{ .Values.build.kaniko.credHelper }}"
      }
    }
