import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { writeFileSync } from 'node:fs';

const packageJson = JSON.parse(
  readFileSync(join(import.meta.dirname, '../package.json'), 'utf-8'),
) as { version: string };

const output = `// Auto-generated by scripts/generate-version.ts — do not edit
export const GENERATED_PACKAGE_VERSION = '${packageJson.version}';
`;

const outputPath = join(import.meta.dirname, '../src/lib/generated-version.ts');
writeFileSync(outputPath, output);
console.log(`Generated ${outputPath} with version ${packageJson.version}`);
