import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));

const packageJson = JSON.parse(
  readFileSync(join(scriptDir, '../package.json'), 'utf-8'),
) as { version: string };

const output = `// Auto-generated by scripts/generate-version.ts — do not edit
export const GENERATED_PACKAGE_VERSION = '${packageJson.version}';
`;

const outputPath = join(scriptDir, '../src/lib/generated-version.ts');

// Only write if content has changed to avoid unnecessary file system churn
const existing = existsSync(outputPath) ? readFileSync(outputPath, 'utf-8') : '';
if (existing !== output) {
  writeFileSync(outputPath, output);
  console.log(`Generated ${outputPath} with version ${packageJson.version}`);
} else {
  console.log(`${outputPath} is up to date (version ${packageJson.version})`);
}
